"""
Aggregation and standards-format export of real analysis results.

- aggregate_interaction_frequencies: per-residue contact-type counts and
  frequencies across batch analyses (pure aggregation of PLIP output).
- export_struct_conn: mmCIF `_struct_conn` records from real contacts,
  importable by PyMOL/ChimeraX/VESTA.

No value in these exports is invented: every record cites a real contact
that PLIP reported for a real structure.
"""

from __future__ import annotations

import csv
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from ..schemas import Contact, Ligand, Structure

_STRUCT_CONN_TO_TYPE = {
    "hydrogen_bond": "hydrog",
    "salt_bridge": "saltbr",
    "metal_coordination": "metalc",
    "halogen_bond": "halog",
    # Disulfide/covalent/metal families map to their own categories;
    # hydrophobic/pi/vdW have no dedicated _struct_conn type and are
    # exported only when a real category exists.
}


def aggregate_interaction_frequencies(
    results: Iterable[Any],
) -> List[Dict[str, Any]]:
    """
    Aggregate contact statistics per residue across batch results.

    `results` items are BatchResult-like objects: success is required, and
    summary.contacts must carry real PLIP records
    (contact_type, protein_residue, protein-residue id via 'residue_id').

    Returns rows sorted by total interactions (descending):
      residue, name, structures, total, per-type counts, frequency.
    Frequency = fraction of successfully analyzed structures in which the
    residue was contacted — computed from the real per-structure data.
    """
    per_residue: Dict[str, Dict[str, Any]] = defaultdict(
        lambda: {"types": defaultdict(int), "structures": set(),
                 "name": ""})
    n_success = 0
    for r in results:
        if not getattr(r, "success", False):
            continue
        summary = getattr(r, "summary", None)
        if summary is None:
            continue
        n_success += 1
        for c in getattr(summary, "contacts", []) or []:
            residue = c.get("protein_residue")
            resid = c.get("residue_id") or c.get("protein_residue_id")
            ctype = c.get("contact_type")
            if residue is None or ctype is None:
                continue
            key = f"{residue}"
            entry = per_residue[key]
            entry["types"][ctype] += 1
            entry["structures"].add(resid)
            if not entry["name"]:
                entry["name"] = residue
            # Track (structure, residue) pairs via a distinct set key.
            entry.setdefault("_pair_keys", set()).add(
                (getattr(r, "structure_id", ""), residue, str(resid)))

    rows = []
    for key, entry in per_residue.items():
        total = sum(entry["types"].values())
        unique_structures = len({pk[0] for pk in entry["_pair_keys"]})
        rows.append({
            "residue": entry["name"],
            "total_interactions": total,
            "structures_contacted": unique_structures,
            "frequency": (round(unique_structures / n_success, 3)
                          if n_success else 0.0),
            "by_type": dict(sorted(entry["types"].items(),
                                   key=lambda kv: -kv[1])),
        })
    rows.sort(key=lambda r: -r["total_interactions"])
    return rows


def export_frequency_csv(rows: List[Dict[str, Any]], path: Path) -> Path:
    """Write aggregation rows as CSV (real data, plain format)."""
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["residue", "total_interactions",
                         "structures_contacted", "frequency",
                         "by_type"])
        for r in rows:
            by_type = ";".join(
                f"{k}:{v}" for k, v in r["by_type"].items())
            writer.writerow([r["residue"], r["total_interactions"],
                             r["structures_contacted"], r["frequency"],
                             by_type])
    return path


def export_struct_conn(
    structure: Structure,
    ligand: Ligand,
    contacts: List[Contact],
    path: Optional[Path] = None,
    pdb_id: str = "",
) -> str:
    """
    Serialize PLIP's real contacts as mmCIF _struct_conn records.

    Only contact types the mmCIF dictionary defines conn_type_id values
    for are exported (hydrog, saltbr, metalc, halog). Each record carries
    the real atoms, distances, and the source PDB entry id.
    """
    lines: List[str] = []
    lines.append("# mmCIF _struct_conn records generated by Ligora")
    lines.append(f"# from real PLIP contact analysis on {pdb_id or structure.id}")
    lines.append(f"# generated {datetime.now(timezone.utc).isoformat()}")
    lines.append("#")
    lines.append("loop_")
    lines.append("_struct_conn.conn_type_id")
    lines.append("_struct_conn.id")
    lines.append("_struct_conn.ptnr1_label_asym_id")
    lines.append("_struct_conn.ptnr1_label_comp_id")
    lines.append("_struct_conn.ptnr1_label_seq_id")
    lines.append("_struct_conn.ptnr1_label_atom_id")
    lines.append("_struct_conn.ptnr2_label_asym_id")
    lines.append("_struct_conn.ptnr2_label_comp_id")
    lines.append("_struct_conn.ptnr2_label_seq_id")
    lines.append("_struct_conn.ptnr2_label_atom_id")
    lines.append("_struct_conn.pdbx_dist_value")
    lines.append("_struct_conn.pdbx_role")

    exported = 0
    for i, c in enumerate(contacts, 1):
        conn_type = _STRUCT_CONN_TO_TYPE.get(c.contact_type.value)
        if conn_type is None:
            continue
        role = c.contact_type.value
        lines.append(
            f"{conn_type} c{i} "
            f"{_cif_token(c.protein_chain_id)} "
            f"{_cif_token(c.protein_residue_name)} "
            f"{c.protein_residue_id} "
            f"{_cif_token(c.protein_atom)} "
            f"{_cif_token(c.ligand_chain_id)} "
            f"{_cif_token(c.ligand_residue_name)} "
            f"{c.ligand_residue_id} "
            f"{_cif_token(c.ligand_atom)} "
            f"{c.distance if c.distance is not None else '?'} "
            f"{_cif_token(role)}")
        exported += 1

    text = "\n".join(lines) + "\n"
    if path is not None:
        path.write_text(text, encoding="utf-8")
    if exported == 0:
        # Honest signal for callers: nothing met the mmCIF conn-type bar.
        text += "# no contacts with mmCIF-mappable conn types\n"
        if path is not None:
            path.write_text(text, encoding="utf-8")
    return text


def _cif_token(value: Any) -> str:
    """Quote when needed per CIF token rules; '?' stays unknown."""
    if value is None or value == "":
        return "?"
    token = str(value)
    if any(ch in token for ch in " \t'\"#$_") or token.startswith(("?", ".")):
        escaped = token.replace("'", "\\'")
        return "'" + escaped + "'"
    return token
